[package]
name = "tmsocial-rust"
version = "0.1.0"
authors = ["Luca Versari <veluca93@gmail.com>"]
edition = "2018"

[dependencies]
diesel = { version = "1.3.3", features = ["postgres"] }
dotenv = "0.13.0"
actix = "0.7.9"
fs_extra = "1.1.0"
tokio-process = "0.2.3"
structopt = "0.2.14"
